name = "KhepriIllustrator"
uuid = "7159cd1a-befd-4126-8a94-9819cf26f52f"
authors = ["António Menezes Leitão <antonio.menezes.leitao@gmail.com>"]
version = "0.1.0"

[deps]
KhepriBase = "4cc0fe96-1163-46f3-ba32-de1e65d9548f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.9"
KhepriBase = "0.5.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
